FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY . .
RUN dotnet restore src/Votji.API.Web.Host/*.csproj

RUN dotnet publish src/Votji.API.Web.Host/*.csproj  -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
EXPOSE 9009/tcp
ENV ASPNETCORE_URLS=http://*:9009
COPY --from=build-env /app/out .
# CMD ASPNETCORE_URLS=http://*:8080 dotnet Votji.API.Web.Host.dll
ENTRYPOINT ["dotnet", "Votji.API.Web.Host.dll"]
 